name: Build Custom ROM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVICE_TREE: https://github.com/whatawurst/android_device_sony_poplar
      DEVICE_BRANCH: lineage-21
      VENDOR_TREE: https://github.com/whatawurst/android_vendor_sony_poplar
      VENDOR_BRANCH: lineage-21
      KERNEL_TREE: https://github.com/whatawurst/android_kernel_sony_msm8998
      KERNEL_BRANCH: lineage-21
      MANIFEST_URL: https://github.com/HorizonDroidLab/manifest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install repo tool
        run: |
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+x ~/.bin/repo
          export PATH="${HOME}/.bin:${PATH}"

      - name: Make ROM directory and change to it
        run: |
          mkdir -p ~/rom && cd ~/rom

      - name: Initialize repo
        run: |
          repo init -u ${{ env.MANIFEST_URL }} -b ${{ env.DEVICE_BRANCH }}
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags

      - name: Clone device, vendor, and kernel trees
        run: |
          cd ~/rom
          git clone ${{ env.DEVICE_TREE }} -b ${{ env.DEVICE_BRANCH }} device/sony/poplar
          git clone ${{ env.VENDOR_TREE }} -b ${{ env.VENDOR_BRANCH }} vendor/sony/poplar
          git clone ${{ env.KERNEL_TREE }} -b ${{ env.KERNEL_BRANCH }} kernel/sony/msm8998

      - name: Set up build environment
        run: |
          cd ~/rom
          source build/envsetup.sh
          lunch lineage_poplar-userdebug

      - name: Build the ROM
        run: |
          cd ~/rom
          mka bacon -j$(nproc)
