name: Build Ancient OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Jakarta  # Set the timezone
      USE_CCACHE: 1
      CCACHE_SIZE: 50G

    steps:
    - name: Set up environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk python3 repo git-core lib32z1-dev lib32ncurses5-dev libbz2-dev lib32stdc++6 libssl-dev curl zlib1g-dev build-essential
        
    - name: Set up Git
 
