name: Build Custom ROM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install openjdk-11-jdk python3 python3-pip git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig libncurses5 repo

    - name: Initialize repo
      run: |
        mkdir -p ~/rom && cd ~/rom
        repo init -u https://github.com/AOSPA/manifest -b pie
        repo sync -j$(nproc)

    - name: Clone device tree
      run: |
        cd ~/rom
        git clone -b lineage-16.1 https://github.com/whatawurst/android_device_sony_poplar.git device/sony/poplar

    - name: Clone vendor tree
      run: |
        cd ~/rom
        git clone -b lineage-16.1 https://github.com/whatawurst/android_vendor_sony_poplar.git vendor/sony/poplar

    - name: Clone kernel tree
      run: |
        cd ~/rom
        git clone -b lineage-16.1 https://github.com/whatawurst/android_kernel_sony_msm8998.git kernel/sony/msm8998

    - name: Start the build
      run: |
        cd ~/rom
        source build/envsetup.sh
        lunch aospa_poplar-userdebug
        make -j$(nproc) bacon

    - name: Upload ROM
      uses: actions/upload-artifact@v2
      with:
        name: ROM
        path: ~/rom/out/target/product/poplar/*.zip
