name: Build Custom ROM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      THREADS: ${{ secrets.NUMBER_OF_PROCESSORS }}

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk python3 python3-venv git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Repo
      run: |
        mkdir -p $HOME/bin
        curl -o $HOME/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod +x $HOME/bin/repo

    - name: Initialize ROM manifest
      run: |
        mkdir -p $HOME/rom
        cd $HOME/rom
        $HOME/bin/repo init -u https://example.com/mirror/platform_manifest.git -b r
      continue-on-error: true  # Continue on error to try multiple times
      retries: 3  # Retry up to 3 times
      timeout-minutes: 10  # Increase timeout if necessary

    - name: Sync ROM source
      run: |
        cd $HOME/rom
        for attempt in {1..5}; do
          $HOME/bin/repo sync -c --no-tags --no-clone-bundle --optimized-fetch --prune -j${{ env.THREADS }} && break || sleep $((attempt * 30)); done
      timeout-minutes: 30  # Increase timeout if necessary

    - name: Clone Device Tree
      run: |
        cd $HOME/rom
        git clone -b lineage-17.1 https://github.com/whatawurst/android_device_sony_poplar.git device/sony/poplar

    - name: Clone Vendor Tree
      run: |
        cd $HOME/rom
        git clone -b lineage-17.1 https://github.com/whatawurst/android_vendor_sony_poplar.git vendor/sony/poplar

    - name: Clone Kernel Tree
      run: |
        cd $HOME/rom
        git clone -b lineage-17.1 https://github.com/whatawurst/android_kernel_sony_msm8998.git kernel/sony/msm8998

    - name: Set up build environment
      run: |
        cd $HOME/rom
        source build/envsetup.sh
        lunch lineage_poplar-userdebug

    - name: Build ROM
      run: |
        cd $HOME/rom
        make bacon -j${{ env.THREADS }}

    - name: Upload ROM
      uses: actions/upload-artifact@v2
      with:
        name: ROM
        path: $HOME/rom/out/target/product/poplar/*.zip
