name: Build Ancient OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Jakarta  # Set the timezone
      USE_CCACHE: 1
      CCACHE_SIZE: 50G

    steps:
    - name: Set up environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk python3 curl git-core lib32z1-dev lib32ncurses5-dev libbz2-dev lib32stdc++6 libssl-dev zlib1g-dev build-essential
        
    - name: Install repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo
        
    - name: Set up Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        
    - name: Check out Ancient OS manifest
      uses: actions/checkout@v2
      with:
        repository: ancient-rom/android_manifest
        path: android

    - name: Initialize repo
      working-directory: android
      run: |
        repo init --depth=1 -u https://github.com/ancient-rom/android_manifest.git -b pie

    - name: Sync repo
      working-directory: android
      run: |
        repo sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --force-sync -j8

    - name: Clone device tree
      run: |
        git clone https://github.com/RinKirito/device_sony_poplar.git android/device/sony/poplar

    - name: Clone vendor tree
      run: |
        git clone https://github.com/AndroidBlobs/vendor_sony_poplar_dsds.git android/vendor/sony/poplar_dsds

    - name: Clone kernel tree
      run: |
        git clone --branch lineage-16.1 https://github.com/whatawurst/android_kernel_sony_msm8998.git android/kernel/sony/msm8998

    - name: Set up CCACHE
      run: |
        ccache -M 50G

    - name: Build ROM
      working-directory: android
      run: |
        source build/envsetup.sh
        lunch ancient_poplar-userdebug
        mka bacon -j$(nproc --all)

    - name: Upload ROM
      uses: actions/upload-artifact@v2
      with:
        name: AncientOS
        path: android/out/target/product/poplar/*.zip
